[package]
name = "mpeg-dash"
version = "0.1.0"
authors = ["Miika Alikirri <miika.alik@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openssl = "0.10.32"
